const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
const MS_PER_DAY = 24 * 60 * 60 * 1000;
const LOCAL_IMAGE_SOURCE = "local";
const REMOTE_IMAGE_SOURCE = "remote";
const SEED_IMAGE_SOURCE = (
  process.env.SEED_IMAGE_SOURCE || LOCAL_IMAGE_SOURCE
).toLowerCase();
const LOCAL_IMAGES_BASE_PATH = "/images";
const REMOTE_IMAGES_STORAGE_PREFIX = "publicImages";
const DEFAULT_REMOTE_IMAGE_BASE_URL = process.env
  .NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
  ? `https://firebasestorage.googleapis.com/v0/b/${process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}/o`
  : "";
const REMOTE_IMAGE_BASE_URL = (
  process.env.SEED_REMOTE_IMAGE_BASE_URL || DEFAULT_REMOTE_IMAGE_BASE_URL
).replace(/\/$/, "");

if (![LOCAL_IMAGE_SOURCE, REMOTE_IMAGE_SOURCE].includes(SEED_IMAGE_SOURCE)) {
  throw new Error(
    `Unsupported SEED_IMAGE_SOURCE "${SEED_IMAGE_SOURCE}". Use "local" or "remote".`,
  );
}

if (SEED_IMAGE_SOURCE === REMOTE_IMAGE_SOURCE && !REMOTE_IMAGE_BASE_URL) {
  throw new Error(
    "SEED_REMOTE_IMAGE_BASE_URL or NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET is required when SEED_IMAGE_SOURCE=remote.",
  );
}

// ── Image pools ───────────────────────────────────────────────────────────────

function pool(dir, prefix, count) {
  return Array.from({ length: count }, (_, i) => {
    const fileName = `${prefix}-${String(i + 1).padStart(2, "0")}.webp`;
    const localPath = `${LOCAL_IMAGES_BASE_PATH}/${dir}/${fileName}`;
    const storagePath = `${REMOTE_IMAGES_STORAGE_PREFIX}/${dir}/${fileName}`;

    return {
      url:
        SEED_IMAGE_SOURCE === REMOTE_IMAGE_SOURCE
          ? `${REMOTE_IMAGE_BASE_URL}/${encodeURIComponent(storagePath)}?alt=media`
          : localPath,
      imagePath:
        SEED_IMAGE_SOURCE === REMOTE_IMAGE_SOURCE ? storagePath : localPath,
    };
  });
}

const IMG = {
  aptExt: pool("exteriors", "apartment", 65),
  hseExt: pool("house-exteriors", "house", 39),
  living: pool("living-rooms", "living-room", 62),
  kitchen: pool("kitchens", "kitchen", 69),
  bedroom: pool("bedrooms", "bedroom", 64),
  bathroom: pool("bathrooms", "bathroom", 68),
  balcony: pool("balconies", "balcony", 49),
  aerial: pool("aerial", "aerial", 53),
  land: pool("land", "land", 15),
  parking: pool("parking", "parking", 12),
};

// Exterior counters — minimise reuse across listings
let aptExtIdx = 0,
  hseExtIdx = 0,
  landIdx = 0,
  parkingIdx = 0;

function exterior(sub) {
  // villas use house-exteriors (villa-exteriors pool not used in seed)
  if (sub === "house" || sub === "villa")
    return IMG.hseExt[hseExtIdx++ % IMG.hseExt.length];
  return IMG.aptExt[aptExtIdx++ % IMG.aptExt.length];
}

// Image count: 10%→1, 15%→2, 25%→3, 50%→4  (based on listingIdx 0-149)
function imageCount(idx) {
  if (idx < 15) return 1;
  if (idx < 38) return 2;
  if (idx < 75) return 3;
  return 4;
}

function buildImages(sub, idx, hasBalcony) {
  // Land and parking: always exactly 1 unique image from dedicated pools
  if (sub === "land") {
    const img = IMG.land[landIdx++ % IMG.land.length];
    return [{ ...img, positionInListing: 0 }];
  }
  if (sub === "parking") {
    const img = IMG.parking[parkingIdx++ % IMG.parking.length];
    return [{ ...img, positionInListing: 0 }];
  }

  const ext = exterior(sub);
  const count = imageCount(idx);
  const imgs = [{ ...ext, positionInListing: 0 }];
  if (count === 1) return imgs;

  const lr = IMG.living[idx % IMG.living.length];
  imgs.push({ ...lr, positionInListing: 1 });
  if (count === 2) return imgs;

  const slot2 =
    idx % 2 === 0
      ? IMG.kitchen[idx % IMG.kitchen.length]
      : IMG.bedroom[idx % IMG.bedroom.length];
  imgs.push({ ...slot2, positionInListing: 2 });
  if (count === 3) return imgs;

  // Slot 3: balcony if the property has one, otherwise vary by type
  let slot3;
  if (hasBalcony) {
    slot3 = IMG.balcony[idx % IMG.balcony.length];
  } else {
    const r = idx % 3;
    if (r === 0) slot3 = IMG.bathroom[idx % IMG.bathroom.length];
    else if (r === 1) slot3 = IMG.bedroom[(idx + 5) % IMG.bedroom.length];
    else slot3 = IMG.kitchen[(idx + 5) % IMG.kitchen.length];
  }
  imgs.push({ ...slot3, positionInListing: 3 });
  return imgs;
}

// ── Price history ─────────────────────────────────────────────────────────────

function euros(v) {
  // Rounding unit scales with price so small prices still get a visible change
  const unit =
    v >= 100000
      ? 1000
      : v >= 20000
        ? 500
        : v >= 5000
          ? 100
          : v >= 1000
            ? 50
            : 10;
  return Math.round(v / unit) * unit;
}

function chronological(history) {
  return [...history].sort(
    (a, b) => a.createdAt.getTime() - b.createdAt.getTime(),
  );
}

function buildPriceHistory(price, idx, listedAt) {
  // listedAt is the listing's createdAt — the first entry must use this date so the
  // app labels it "Listed". Every listing gets at least 2 entries.
  // Anchor days are computed proportionally so dates are always strictly increasing
  // regardless of how long the listing has been live.
  const now = Date.now();
  const msListed = now - listedAt.getTime();
  const daysListed = Math.floor(msListed / MS_PER_DAY);

  function after(d) {
    return new Date(listedAt.getTime() + d * MS_PER_DAY);
  }
  function afterMs(ms) {
    return new Date(listedAt.getTime() + ms);
  }

  // <5 days: change placed at midpoint of elapsed time
  if (daysListed < 5) {
    const p0 = euros(price * (1.03 + (idx % 5) * 0.01));
    return chronological([
      { currency: "EUR", price: p0, tax: null, createdAt: listedAt },
      {
        currency: "EUR",
        price: price,
        tax: null,
        createdAt: afterMs(Math.floor(msListed * 0.5)),
      },
    ]);
  }

  // Proportional anchors — always strictly increasing, always before "now"
  const w = daysListed - 1; // available days (1-day buffer before now)
  const d1 = Math.max(1, Math.floor(w * 0.3));
  const d2 = Math.max(d1 + 3, Math.floor(w * 0.62));
  const d3 = Math.max(d2 + 3, Math.floor(w * 0.84));

  // <20 days: 2 entries only (not enough room for meaningful multi-step history)
  if (daysListed < 20) {
    const p0 = euros(price * (1.05 + (idx % 8) * 0.01));
    return chronological([
      { currency: "EUR", price: p0, tax: null, createdAt: listedAt },
      { currency: "EUR", price: price, tax: null, createdAt: after(d1) },
    ]);
  }

  const scenario = idx % 10;

  if (scenario <= 6) {
    // 70%: listed high → mid reduction → current
    const p0 = euros(price * (1.08 + (idx % 10) * 0.01));
    const p1 = euros(price * (1.03 + (idx % 5) * 0.01));
    return chronological([
      { currency: "EUR", price: p0, tax: null, createdAt: listedAt },
      { currency: "EUR", price: p1, tax: null, createdAt: after(d1) },
      { currency: "EUR", price: price, tax: null, createdAt: after(d2) },
    ]);
  }

  if (scenario <= 8) {
    // 20%: 4 entries with 3 step-down reductions (only when listing is old enough)
    if (daysListed >= 40) {
      const p0 = euros(price * (1.15 + (idx % 8) * 0.01));
      const p1 = euros(price * (1.08 + (idx % 6) * 0.01));
      const p2 = euros(price * (1.03 + (idx % 4) * 0.01));
      return chronological([
        { currency: "EUR", price: p0, tax: null, createdAt: listedAt },
        { currency: "EUR", price: p1, tax: null, createdAt: after(d1) },
        { currency: "EUR", price: p2, tax: null, createdAt: after(d2) },
        { currency: "EUR", price: price, tax: null, createdAt: after(d3) },
      ]);
    }
    // Fall back to 3 entries for younger listings
    const p0 = euros(price * (1.08 + (idx % 10) * 0.01));
    const p1 = euros(price * (1.03 + (idx % 5) * 0.01));
    return chronological([
      { currency: "EUR", price: p0, tax: null, createdAt: listedAt },
      { currency: "EUR", price: p1, tax: null, createdAt: after(d1) },
      { currency: "EUR", price: price, tax: null, createdAt: after(d2) },
    ]);
  }

  // 10%: listed slightly lower → small increase → current (higher)
  const p0 = euros(price * (0.94 + (idx % 5) * 0.01));
  const p1 = euros(price * (0.97 + (idx % 4) * 0.01));
  return chronological([
    { currency: "EUR", price: p0, tax: null, createdAt: listedAt },
    { currency: "EUR", price: p1, tax: null, createdAt: after(d1) },
    { currency: "EUR", price: price, tax: null, createdAt: after(d2) },
  ]);
}

// ── Description & key points ──────────────────────────────────────────────────

function buildDescription(p) {
  if (p.sub === "land") {
    const use = p.zone ? p.zone : "residential or investment";
    return (
      `Building plot for sale in ${p.nbhd}, ${p.city}. ` +
      `The land spans ${p.area} sqm and is suitable for ${use} development. ` +
      `Fully regulated with all utilities available nearby. ` +
      `Prime location in ${p.nbhd} with excellent transport links and infrastructure.`
    );
  }
  if (p.sub === "parking") {
    return (
      `Parking space for sale in ${p.nbhd}, ${p.city}. ` +
      `Secure ${p.covered ? "covered " : ""}parking spot of ${p.area} sqm, ` +
      `located in a ${p.indoor ? "underground garage" : "surface car park"} with 24/7 access. ` +
      `Ideal for residents and investors in ${p.nbhd}.`
    );
  }
  const type =
    p.sub === "villa" ? "villa" : p.sub === "house" ? "house" : "apartment";
  const action = p.lt === "RENT" ? "rent" : "sale";
  const balcony = p.aOut ? ` with a ${p.aOut} sqm balcony` : "";
  const garden = p.aLand ? ` set on a ${p.aLand} sqm private plot` : "";
  const bedLabel = p.bed === 0 ? "Studio" : `${p.bed}-bedroom`;
  const floorLine = p.fl ? `, floor ${p.fl} of ${p.tfl}` : "";
  const furnished =
    p.int === "FURNISHED"
      ? "fully furnished and move-in ready"
      : "unfurnished — ideal for buyers who prefer their own interior";
  const condition = {
    EXCELLENT: "in excellent condition with modern finishes",
    GOOD: "in good overall condition",
    FAIR: "in fair condition with some cosmetic updates needed",
  }[p.upk];
  return (
    `${bedLabel} ${type} for ${action} in ${p.nbhd}, ${p.city}${balcony}${garden}. ` +
    `The property spans ${p.area} sqm${p.aLiv ? ` (${p.aLiv} sqm living area)` : ""}${floorLine}, ` +
    `${furnished} and ${condition}. ` +
    `Conveniently located in ${p.nbhd} with easy access to public transport, shops, and green spaces.`
  );
}

function buildKeyPoints(p) {
  if (p.sub === "land") {
    return [
      ["Land area", `${p.area} sqm of regulated land ready for development.`],
      [
        "Prime location",
        `Located in ${p.nbhd}, ${p.city} — well connected and in demand.`,
      ],
      [
        "Utilities",
        "Water, electricity and road access available at the plot boundary.",
      ],
    ];
  }
  if (p.sub === "parking") {
    return [
      [
        "Secure parking",
        `${p.covered ? "Covered" : "Surface"} parking space with ${p.indoor ? "underground garage" : "barrier"} access.`,
      ],
      [
        "Prime location",
        `Located in ${p.nbhd}, ${p.city} — high-demand area for parking.`,
      ],
      [
        "Low maintenance",
        "No maintenance fees beyond standard building costs.",
      ],
    ];
  }
  const kp = [];
  if (p.aOut)
    kp.push([
      "Outdoor space",
      `${p.aOut} sqm balcony or terrace with natural light.`,
    ]);
  if (p.park)
    kp.push([
      "Parking included",
      `${p.park} dedicated parking space${p.park > 1 ? "s" : ""} included.`,
    ]);
  kp.push([
    "Prime location",
    `Located in ${p.nbhd}, ${p.city} — close to transport, shops and everyday services.`,
  ]);
  if (p.heat === "CENTRAL")
    kp.push([
      "Central heating",
      "Building-wide central heating with individual metering.",
    ]);
  else
    kp.push([
      "Independent heating",
      "Gas boiler providing full control over heating costs.",
    ]);
  if (p.built >= 2015)
    kp.push([
      "Modern build",
      `Constructed in ${p.built} with contemporary materials and finishes.`,
    ]);
  if (p.aLand)
    kp.push([
      "Private garden",
      `${p.aLand} sqm of private outdoor land — ideal for outdoor living.`,
    ]);
  return kp.slice(0, 3);
}

// ── Users ─────────────────────────────────────────────────────────────────────

const USERS = [
  {
    displayName: "Maria Ivanova",
    email: "maria@homfli.com",
    phone: "+359 88 123 4567",
    addr: "ul. Vitosha 24, Sofia",
  },
  {
    displayName: "Georgi Petrov",
    email: "georgi@homfli.com",
    phone: "+359 87 234 5678",
    addr: "bul. Bulgaria 48, Plovdiv",
  },
  {
    displayName: "Stefan Todorov",
    email: "stefan@homfli.com",
    phone: "+359 89 345 6789",
    addr: "ul. Knyaz Boris I 12, Varna",
  },
  {
    displayName: "Elena Stoyanova",
    email: "elena@homfli.com",
    phone: "+359 88 456 7890",
    addr: "bul. San Stefano 7, Burgas",
  },
  {
    displayName: "Nikolay Dimitrov",
    email: "nikolay@homfli.com",
    phone: "+359 87 567 8901",
    addr: "ul. Aleksandrovska 33, Ruse",
  },
  {
    displayName: "Desislava Marinova",
    email: "desislava@homfli.com",
    phone: "+359 89 678 9012",
    addr: "ul. Vasil Levski 15, Pleven",
  },
  {
    displayName: "Viktor Kolev",
    email: "viktor@homfli.com",
    phone: "+359 88 789 0123",
    addr: "ul. Tsar Simeon 8, Sliven",
  },
  {
    displayName: "Kalina Vasileva",
    email: "kalina@homfli.com",
    phone: "+359 87 890 1234",
    addr: "ul. Oborishte 5, Sofia",
  },
  {
    displayName: "Aleksandar Hristov",
    email: "aleksandar@homfli.com",
    phone: "+359 89 901 2345",
    addr: "ul. Bratya Shkorpil 19, Varna",
  },
  {
    displayName: "Borislava Petrova",
    email: "borislava@homfli.com",
    phone: "+359 88 012 3456",
    addr: "ul. Filip Kutev 3, Sofia",
  },
];

// ── Properties ────────────────────────────────────────────────────────────────
// sub: apartment | house | villa
// lt:  SELL | RENT
// fl/tfl: floor / total floors (apartments only)
// aOut: balcony/terrace sqm | aLand: plot sqm | aLiv: living area sqm | aGar: garage sqm
// int: FURNISHED | UNFURNISHED  |  upk: EXCELLENT | GOOD | FAIR  |  heat: CENTRAL | BOILER

const PROPS = [
  // ── Sofia · Lozenets ────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Krichim",
    hn: "8",
    pc: "1164",
    lat: 42.6743,
    lng: 23.3237,
    area: 128,
    aLiv: 112,
    aOut: 12,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 7,
    tfl: 10,
    built: 2017,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 285000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Krichim",
    hn: "14",
    pc: "1164",
    lat: 42.6751,
    lng: 23.3245,
    area: 108,
    aLiv: 93,
    aOut: 10,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 2,
    fl: 3,
    tfl: 6,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 238000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Krichim",
    hn: "22",
    pc: "1164",
    lat: 42.6738,
    lng: 23.3228,
    area: 162,
    aLiv: 138,
    aOut: 22,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 9,
    tfl: 9,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 385000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Krichim",
    hn: "31",
    pc: "1164",
    lat: 42.6755,
    lng: 23.3251,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 500,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2013,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 425000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Krichim",
    hn: "45",
    pc: "1164",
    lat: 42.6748,
    lng: 23.326,
    area: 280,
    aLiv: 240,
    aOut: 50,
    aLand: 800,
    aGar: 30,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2019,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 650000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Krichim",
    hn: "52",
    pc: "1164",
    lat: 42.676,
    lng: 23.327,
    area: 350,
    aLiv: 300,
    aOut: 65,
    aLand: 1100,
    aGar: 40,
    rooms: 7,
    bed: 6,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2021,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 3,
    price: 820000,
  },

  // ── Sofia · Mladost ──────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Mladost",
    street: "bul. Aleksandar Malinov",
    hn: "16",
    pc: "1715",
    lat: 42.6258,
    lng: 23.3796,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 9,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 142000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Sofia",
    nbhd: "Mladost",
    street: "bul. Aleksandar Malinov",
    hn: "24",
    pc: "1715",
    lat: 42.6264,
    lng: 23.3804,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 5,
    tfl: 8,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 1100,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Mladost",
    street: "bul. Aleksandar Malinov",
    hn: "38",
    pc: "1715",
    lat: 42.627,
    lng: 23.3812,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 112000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Mladost",
    street: "bul. Aleksandar Malinov",
    hn: "55",
    pc: "1715",
    lat: 42.6276,
    lng: 23.382,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 340,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 268000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Mladost",
    street: "bul. Aleksandar Malinov",
    hn: "63",
    pc: "1715",
    lat: 42.6282,
    lng: 23.3828,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 500,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 345000,
  },

  // ── Sofia · Vitosha ──────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Vitosha",
    street: "ul. Simeonsko shose",
    hn: "5",
    pc: "1700",
    lat: 42.6412,
    lng: 23.2987,
    area: 128,
    aLiv: 112,
    aOut: 12,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 4,
    tfl: 6,
    built: 2017,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 272000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Vitosha",
    street: "ul. Simeonsko shose",
    hn: "18",
    pc: "1700",
    lat: 42.642,
    lng: 23.2995,
    area: 224,
    aLiv: 186,
    aOut: 38,
    aLand: 540,
    aGar: 26,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2021,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 2,
    price: 490000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Vitosha",
    street: "ul. Simeonsko shose",
    hn: "27",
    pc: "1700",
    lat: 42.6428,
    lng: 23.3003,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 500,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2013,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 398000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Vitosha",
    street: "ul. Simeonsko shose",
    hn: "36",
    pc: "1700",
    lat: 42.6436,
    lng: 23.3011,
    area: 320,
    aLiv: 270,
    aOut: 55,
    aLand: 900,
    aGar: 35,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 3,
    price: 730000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Vitosha",
    street: "ul. Simeonsko shose",
    hn: "44",
    pc: "1700",
    lat: 42.6444,
    lng: 23.3019,
    area: 260,
    aLiv: 220,
    aOut: 48,
    aLand: 750,
    aGar: 30,
    rooms: 6,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 548000,
  },

  // ── Sofia · Center ───────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Center",
    street: "bul. Vitosha",
    hn: "12",
    pc: "1000",
    lat: 42.6977,
    lng: 23.3219,
    area: 128,
    aLiv: 112,
    aOut: 12,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 5,
    tfl: 8,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 392000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Center",
    street: "bul. Vitosha",
    hn: "28",
    pc: "1000",
    lat: 42.6985,
    lng: 23.3227,
    area: 162,
    aLiv: 138,
    aOut: 22,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 8,
    tfl: 8,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 455000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Sofia",
    nbhd: "Center",
    street: "bul. Vitosha",
    hn: "35",
    pc: "1000",
    lat: 42.6993,
    lng: 23.3235,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 6,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 1400,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Center",
    street: "ul. Oborishte",
    hn: "7",
    pc: "1000",
    lat: 42.6969,
    lng: 23.3211,
    area: 148,
    aLiv: 122,
    aOut: 18,
    aLand: 280,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2008,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 1,
    price: 365000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Center",
    street: "ul. Oborishte",
    hn: "15",
    pc: "1000",
    lat: 42.6961,
    lng: 23.3203,
    area: 240,
    aLiv: 200,
    aOut: 40,
    aLand: 450,
    aGar: 25,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2019,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 2,
    price: 525000,
  },

  // ── Sofia · Iztok ────────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Iztok",
    street: "ul. Lyubomir Lulchev",
    hn: "3",
    pc: "1113",
    lat: 42.685,
    lng: 23.345,
    area: 128,
    aLiv: 112,
    aOut: 12,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 6,
    tfl: 9,
    built: 2017,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 315000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Iztok",
    street: "ul. Lyubomir Lulchev",
    hn: "11",
    pc: "1113",
    lat: 42.6858,
    lng: 23.3458,
    area: 108,
    aLiv: 93,
    aOut: 10,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 2,
    fl: 3,
    tfl: 7,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 248000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Iztok",
    street: "ul. Lyubomir Lulchev",
    hn: "19",
    pc: "1113",
    lat: 42.6866,
    lng: 23.3466,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 500,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 435000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Iztok",
    street: "ul. Lyubomir Lulchev",
    hn: "27",
    pc: "1113",
    lat: 42.6874,
    lng: 23.3474,
    area: 300,
    aLiv: 255,
    aOut: 55,
    aLand: 850,
    aGar: 32,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 668000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Iztok",
    street: "ul. Lyubomir Lulchev",
    hn: "35",
    pc: "1113",
    lat: 42.6882,
    lng: 23.3482,
    area: 380,
    aLiv: 320,
    aOut: 70,
    aLand: 1200,
    aGar: 40,
    rooms: 7,
    bed: 6,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2022,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 3,
    price: 862000,
  },

  // ── Sofia · Borovo ───────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Borovo",
    street: "bul. Nadezhda",
    hn: "8",
    pc: "1618",
    lat: 42.6605,
    lng: 23.288,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 145000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Borovo",
    street: "bul. Nadezhda",
    hn: "16",
    pc: "1618",
    lat: 42.6613,
    lng: 23.2888,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 4,
    tfl: 7,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 106000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Borovo",
    street: "bul. Nadezhda",
    hn: "25",
    pc: "1618",
    lat: 42.6621,
    lng: 23.2896,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 340,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 270000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Borovo",
    street: "bul. Nadezhda",
    hn: "33",
    pc: "1618",
    lat: 42.6629,
    lng: 23.2904,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 480,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 335000,
  },

  // ── Sofia · Krasno Selo ──────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Krasno Selo",
    street: "ul. Filip Kutev",
    hn: "4",
    pc: "1407",
    lat: 42.671,
    lng: 23.302,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 8,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 148000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Krasno Selo",
    street: "ul. Filip Kutev",
    hn: "12",
    pc: "1407",
    lat: 42.6718,
    lng: 23.3028,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 5,
    tfl: 8,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 165000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Krasno Selo",
    street: "ul. Filip Kutev",
    hn: "21",
    pc: "1407",
    lat: 42.6726,
    lng: 23.3036,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 340,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2009,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 265000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Krasno Selo",
    street: "ul. Filip Kutev",
    hn: "30",
    pc: "1407",
    lat: 42.6734,
    lng: 23.3044,
    area: 245,
    aLiv: 205,
    aOut: 42,
    aLand: 700,
    aGar: 28,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 498000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Krasno Selo",
    street: "ul. Filip Kutev",
    hn: "38",
    pc: "1407",
    lat: 42.6742,
    lng: 23.3052,
    area: 312,
    aLiv: 265,
    aOut: 58,
    aLand: 950,
    aGar: 35,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2022,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 3,
    price: 645000,
  },

  // ── Sofia · Studentski Grad ──────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Studentski Grad",
    street: "bul. Kliment Ohridski",
    hn: "3",
    pc: "1756",
    lat: 42.6518,
    lng: 23.3542,
    area: 42,
    aLiv: 36,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 1,
    bed: 0,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2019,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 78000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Studentski Grad",
    street: "bul. Kliment Ohridski",
    hn: "11",
    pc: "1756",
    lat: 42.6526,
    lng: 23.355,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 98000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Sofia",
    nbhd: "Studentski Grad",
    street: "bul. Kliment Ohridski",
    hn: "19",
    pc: "1756",
    lat: 42.6534,
    lng: 23.3558,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 850,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Studentski Grad",
    street: "bul. Kliment Ohridski",
    hn: "27",
    pc: "1756",
    lat: 42.6542,
    lng: 23.3566,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 5,
    tfl: 9,
    built: 2015,
    int: "UNFURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 1,
    price: 148000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Studentski Grad",
    street: "bul. Kliment Ohridski",
    hn: "35",
    pc: "1756",
    lat: 42.655,
    lng: 23.3574,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 320,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 255000,
  },

  // ── Plovdiv · Kapana ─────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Kapana",
    street: "ul. Zlatarska",
    hn: "5",
    pc: "4000",
    lat: 42.1497,
    lng: 24.7481,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 6,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 128000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Kapana",
    street: "ul. Zlatarska",
    hn: "13",
    pc: "4000",
    lat: 42.1505,
    lng: 24.7489,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 108000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Plovdiv",
    nbhd: "Kapana",
    street: "ul. Zlatarska",
    hn: "21",
    pc: "4000",
    lat: 42.1513,
    lng: 24.7497,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 1,
    tfl: 4,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 650,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Kapana",
    street: "ul. Zlatarska",
    hn: "30",
    pc: "4000",
    lat: 42.1521,
    lng: 24.7505,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 320,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2008,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 235000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Kapana",
    street: "ul. Zlatarska",
    hn: "38",
    pc: "4000",
    lat: 42.1529,
    lng: 24.7513,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 480,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2012,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 315000,
  },

  // ── Plovdiv · Trakia ─────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Trakia",
    street: "bul. Osvobozhdenie",
    hn: "7",
    pc: "4023",
    lat: 42.135,
    lng: 24.758,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 115000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Trakia",
    street: "bul. Osvobozhdenie",
    hn: "15",
    pc: "4023",
    lat: 42.1358,
    lng: 24.7588,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 7,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 98000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Plovdiv",
    nbhd: "Trakia",
    street: "bul. Osvobozhdenie",
    hn: "23",
    pc: "4023",
    lat: 42.1366,
    lng: 24.7596,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 3,
    tfl: 6,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 580,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Trakia",
    street: "bul. Osvobozhdenie",
    hn: "32",
    pc: "4023",
    lat: 42.1374,
    lng: 24.7604,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 340,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2009,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 220000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Trakia",
    street: "bul. Osvobozhdenie",
    hn: "40",
    pc: "4023",
    lat: 42.1382,
    lng: 24.7612,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 500,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 290000,
  },

  // ── Plovdiv · Karshiyaka ─────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Karshiyaka",
    street: "bul. Bulgaria",
    hn: "6",
    pc: "4003",
    lat: 42.1639,
    lng: 24.7411,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 96000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Karshiyaka",
    street: "bul. Bulgaria",
    hn: "14",
    pc: "4003",
    lat: 42.1647,
    lng: 24.7419,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 7,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 112000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Karshiyaka",
    street: "bul. Bulgaria",
    hn: "22",
    pc: "4003",
    lat: 42.1655,
    lng: 24.7427,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 1,
    tfl: 4,
    built: 2008,
    int: "UNFURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 0,
    price: 72000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Karshiyaka",
    street: "bul. Bulgaria",
    hn: "31",
    pc: "4003",
    lat: 42.1663,
    lng: 24.7435,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 320,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2007,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 228000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Karshiyaka",
    street: "bul. Bulgaria",
    hn: "40",
    pc: "4003",
    lat: 42.1671,
    lng: 24.7443,
    area: 240,
    aLiv: 200,
    aOut: 40,
    aLand: 650,
    aGar: 28,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 385000,
  },

  // ── Plovdiv · Center ─────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Center",
    street: "ul. Hristo Botev",
    hn: "8",
    pc: "4000",
    lat: 42.145,
    lng: 24.75,
    area: 128,
    aLiv: 112,
    aOut: 12,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 5,
    tfl: 7,
    built: 2017,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 188000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Center",
    street: "ul. Hristo Botev",
    hn: "16",
    pc: "4000",
    lat: 42.1458,
    lng: 24.7508,
    area: 108,
    aLiv: 93,
    aOut: 10,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 2,
    fl: 3,
    tfl: 6,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 162000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Plovdiv",
    nbhd: "Center",
    street: "ul. Hristo Botev",
    hn: "24",
    pc: "4000",
    lat: 42.1466,
    lng: 24.7516,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2014,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 850,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Center",
    street: "ul. Hristo Botev",
    hn: "33",
    pc: "4000",
    lat: 42.1474,
    lng: 24.7524,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 450,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 2,
    price: 298000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Center",
    street: "ul. Hristo Botev",
    hn: "41",
    pc: "4000",
    lat: 42.1482,
    lng: 24.7532,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 320,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2007,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 232000,
  },

  // ── Varna · Sea Garden ───────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Sea Garden",
    street: "ul. Preslav",
    hn: "4",
    pc: "9000",
    lat: 43.2028,
    lng: 27.9189,
    area: 162,
    aLiv: 138,
    aOut: 22,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 9,
    tfl: 9,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 290000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Sea Garden",
    street: "ul. Preslav",
    hn: "12",
    pc: "9000",
    lat: 43.2036,
    lng: 27.9197,
    area: 108,
    aLiv: 93,
    aOut: 10,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 2,
    fl: 5,
    tfl: 8,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 218000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Varna",
    nbhd: "Sea Garden",
    street: "ul. Preslav",
    hn: "21",
    pc: "9000",
    lat: 43.2044,
    lng: 27.9205,
    area: 224,
    aLiv: 186,
    aOut: 38,
    aLand: 540,
    aGar: 26,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2019,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 2,
    price: 425000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Varna",
    nbhd: "Sea Garden",
    street: "ul. Preslav",
    hn: "30",
    pc: "9000",
    lat: 43.2052,
    lng: 27.9213,
    area: 380,
    aLiv: 320,
    aOut: 70,
    aLand: 1100,
    aGar: 40,
    rooms: 7,
    bed: 6,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2021,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 3,
    price: 820000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Varna",
    nbhd: "Sea Garden",
    street: "ul. Preslav",
    hn: "38",
    pc: "9000",
    lat: 43.206,
    lng: 27.9221,
    area: 310,
    aLiv: 265,
    aOut: 58,
    aLand: 900,
    aGar: 35,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 635000,
  },

  // ── Varna · Levski ───────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Levski",
    street: "bul. Slivnitsa",
    hn: "5",
    pc: "9010",
    lat: 43.2149,
    lng: 27.9438,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 155000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Levski",
    street: "bul. Slivnitsa",
    hn: "13",
    pc: "9010",
    lat: 43.2157,
    lng: 27.9446,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 128000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Varna",
    nbhd: "Levski",
    street: "bul. Slivnitsa",
    hn: "21",
    pc: "9010",
    lat: 43.2165,
    lng: 27.9454,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 700,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Levski",
    street: "bul. Slivnitsa",
    hn: "29",
    pc: "9010",
    lat: 43.2173,
    lng: 27.9462,
    area: 42,
    aLiv: 36,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 1,
    bed: 0,
    bath: 1,
    fl: 1,
    tfl: 5,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 68000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Varna",
    nbhd: "Levski",
    street: "bul. Slivnitsa",
    hn: "38",
    pc: "9010",
    lat: 43.2181,
    lng: 27.947,
    area: 260,
    aLiv: 220,
    aOut: 48,
    aLand: 720,
    aGar: 30,
    rooms: 6,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2019,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 458000,
  },

  // ── Varna · Vladislav Varnenchik ─────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Vladislav Varnenchik",
    street: "bul. Vladislav Varnenchik",
    hn: "6",
    pc: "9020",
    lat: 43.228,
    lng: 27.895,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2014,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 138000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Vladislav Varnenchik",
    street: "bul. Vladislav Varnenchik",
    hn: "14",
    pc: "9020",
    lat: 43.2288,
    lng: 27.8958,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 116000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Vladislav Varnenchik",
    street: "bul. Vladislav Varnenchik",
    hn: "22",
    pc: "9020",
    lat: 43.2296,
    lng: 27.8966,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 1,
    tfl: 5,
    built: 2009,
    int: "UNFURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 0,
    price: 86000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Varna",
    nbhd: "Vladislav Varnenchik",
    street: "bul. Vladislav Varnenchik",
    hn: "31",
    pc: "9020",
    lat: 43.2304,
    lng: 27.8974,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 340,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2009,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 228000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Varna",
    nbhd: "Vladislav Varnenchik",
    street: "bul. Vladislav Varnenchik",
    hn: "40",
    pc: "9020",
    lat: 43.2312,
    lng: 27.8982,
    area: 280,
    aLiv: 238,
    aOut: 52,
    aLand: 800,
    aGar: 32,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2017,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 495000,
  },

  // ── Burgas · Lazur ───────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Lazur",
    street: "ul. Koprivshtitsa",
    hn: "3",
    pc: "8001",
    lat: 42.5073,
    lng: 27.4756,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 118000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Lazur",
    street: "ul. Koprivshtitsa",
    hn: "11",
    pc: "8001",
    lat: 42.5081,
    lng: 27.4764,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 98000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Burgas",
    nbhd: "Lazur",
    street: "ul. Koprivshtitsa",
    hn: "19",
    pc: "8001",
    lat: 42.5089,
    lng: 27.4772,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 550,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Lazur",
    street: "ul. Koprivshtitsa",
    hn: "27",
    pc: "8001",
    lat: 42.5097,
    lng: 27.478,
    area: 42,
    aLiv: 36,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 1,
    bed: 0,
    bath: 1,
    fl: 1,
    tfl: 5,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 55000,
  },

  // ── Burgas · Sea Park ────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Sea Park",
    street: "bul. San Stefano",
    hn: "5",
    pc: "8000",
    lat: 42.492,
    lng: 27.462,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 5,
    tfl: 8,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 128000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Sea Park",
    street: "bul. San Stefano",
    hn: "14",
    pc: "8000",
    lat: 42.4928,
    lng: 27.4628,
    area: 198,
    aLiv: 165,
    aOut: 34,
    aLand: 480,
    aGar: 22,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 308000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Sea Park",
    street: "bul. San Stefano",
    hn: "23",
    pc: "8000",
    lat: 42.4936,
    lng: 27.4636,
    area: 310,
    aLiv: 265,
    aOut: 58,
    aLand: 880,
    aGar: 35,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 588000,
  },

  // ── Burgas · Slaveikov ───────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Slaveikov",
    street: "ul. Slaveikov",
    hn: "6",
    pc: "8003",
    lat: 42.502,
    lng: 27.47,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 92000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Slaveikov",
    street: "ul. Slaveikov",
    hn: "14",
    pc: "8003",
    lat: 42.5028,
    lng: 27.4708,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 68000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Slaveikov",
    street: "ul. Slaveikov",
    hn: "22",
    pc: "8003",
    lat: 42.5036,
    lng: 27.4716,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 320,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2008,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 198000,
  },

  // ── Ruse · Center ────────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Center",
    street: "ul. Aleksandrovska",
    hn: "10",
    pc: "7000",
    lat: 43.8564,
    lng: 25.9739,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 7,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 95000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Center",
    street: "ul. Aleksandrovska",
    hn: "18",
    pc: "7000",
    lat: 43.8572,
    lng: 25.9747,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 82000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Ruse",
    nbhd: "Center",
    street: "ul. Aleksandrovska",
    hn: "26",
    pc: "7000",
    lat: 43.858,
    lng: 25.9755,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 1,
    tfl: 5,
    built: 2008,
    int: "FURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 0,
    price: 420,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Center",
    street: "ul. Aleksandrovska",
    hn: "35",
    pc: "7000",
    lat: 43.8588,
    lng: 25.9763,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 300,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2007,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 185000,
  },

  // ── Ruse · Druzhba ───────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Druzhba",
    street: "bul. Treti Mart",
    hn: "4",
    pc: "7012",
    lat: 43.845,
    lng: 25.958,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 6,
    built: 2009,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 74000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Druzhba",
    street: "bul. Treti Mart",
    hn: "12",
    pc: "7012",
    lat: 43.8458,
    lng: 25.9588,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2007,
    int: "UNFURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 0,
    price: 56000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Druzhba",
    street: "bul. Treti Mart",
    hn: "21",
    pc: "7012",
    lat: 43.8466,
    lng: 25.9596,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 300,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2006,
    int: "FURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 1,
    price: 165000,
  },

  // ── Pleven · Center ──────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Pleven",
    nbhd: "Center",
    street: "ul. Vasil Levski",
    hn: "8",
    pc: "5800",
    lat: 43.4172,
    lng: 24.6064,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 72000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Pleven",
    nbhd: "Center",
    street: "ul. Vasil Levski",
    hn: "16",
    pc: "5800",
    lat: 43.418,
    lng: 24.6072,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 56000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Pleven",
    nbhd: "Center",
    street: "ul. Vasil Levski",
    hn: "24",
    pc: "5800",
    lat: 43.4188,
    lng: 24.608,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2014,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 380,
  },

  // ── Pleven · Storgozia ───────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Pleven",
    nbhd: "Storgozia",
    street: "ul. Georgi Kochev",
    hn: "5",
    pc: "5805",
    lat: 43.405,
    lng: 24.598,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 1,
    tfl: 4,
    built: 2007,
    int: "UNFURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 0,
    price: 52000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Pleven",
    nbhd: "Storgozia",
    street: "ul. Georgi Kochev",
    hn: "13",
    pc: "5805",
    lat: 43.4058,
    lng: 24.5988,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 300,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2005,
    int: "FURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 1,
    price: 168000,
  },

  // ── Sliven · Center ──────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sliven",
    nbhd: "Center",
    street: "ul. Tsar Simeon",
    hn: "6",
    pc: "8800",
    lat: 42.6861,
    lng: 26.3228,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2009,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 68000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Sliven",
    nbhd: "Center",
    street: "ul. Tsar Simeon",
    hn: "14",
    pc: "8800",
    lat: 42.6869,
    lng: 26.3236,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 3,
    tfl: 6,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 320,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sliven",
    nbhd: "Center",
    street: "ul. Tsar Simeon",
    hn: "22",
    pc: "8800",
    lat: 42.6877,
    lng: 26.3244,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 300,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2006,
    int: "FURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 1,
    price: 155000,
  },

  // ── Sofia · Oborishte ────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Oborishte",
    street: "ul. Oborishte",
    hn: "10",
    pc: "1504",
    lat: 42.6935,
    lng: 23.337,
    area: 110,
    aLiv: 95,
    aOut: 10,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 2,
    fl: 4,
    tfl: 7,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 268000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Oborishte",
    street: "ul. Oborishte",
    hn: "18",
    pc: "1504",
    lat: 42.6943,
    lng: 23.3378,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 195000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Sofia",
    nbhd: "Oborishte",
    street: "ul. Oborishte",
    hn: "26",
    pc: "1504",
    lat: 42.6951,
    lng: 23.3386,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 8,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 1300,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Oborishte",
    street: "ul. Oborishte",
    hn: "35",
    pc: "1504",
    lat: 42.6959,
    lng: 23.3394,
    area: 165,
    aLiv: 138,
    aOut: 28,
    aLand: 380,
    aGar: 20,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 355000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Oborishte",
    street: "ul. Oborishte",
    hn: "44",
    pc: "1504",
    lat: 42.6967,
    lng: 23.3402,
    area: 295,
    aLiv: 250,
    aOut: 52,
    aLand: 780,
    aGar: 32,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 620000,
  },

  // ── Sofia · Nadezhda ─────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Nadezhda",
    street: "bul. Rositsa",
    hn: "5",
    pc: "1220",
    lat: 42.7178,
    lng: 23.2889,
    area: 68,
    aLiv: 58,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 3,
    tfl: 8,
    built: 2014,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 108000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Nadezhda",
    street: "bul. Rositsa",
    hn: "13",
    pc: "1220",
    lat: 42.7186,
    lng: 23.2897,
    area: 52,
    aLiv: 44,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 88000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Nadezhda",
    street: "bul. Rositsa",
    hn: "21",
    pc: "1220",
    lat: 42.7194,
    lng: 23.2905,
    area: 88,
    aLiv: 75,
    aOut: 7,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 5,
    tfl: 9,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 138000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Nadezhda",
    street: "bul. Rositsa",
    hn: "30",
    pc: "1220",
    lat: 42.7202,
    lng: 23.2913,
    area: 145,
    aLiv: 120,
    aOut: 20,
    aLand: 310,
    aGar: 16,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2009,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 248000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Nadezhda",
    street: "bul. Rositsa",
    hn: "38",
    pc: "1220",
    lat: 42.721,
    lng: 23.2921,
    area: 188,
    aLiv: 158,
    aOut: 32,
    aLand: 450,
    aGar: 20,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2013,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 298000,
  },

  // ── Sofia · Geo Milev ────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Geo Milev",
    street: "ul. Kosta Lulchev",
    hn: "6",
    pc: "1111",
    lat: 42.6922,
    lng: 23.3596,
    area: 82,
    aLiv: 70,
    aOut: 7,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 175000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Geo Milev",
    street: "ul. Kosta Lulchev",
    hn: "14",
    pc: "1111",
    lat: 42.693,
    lng: 23.3604,
    area: 105,
    aLiv: 90,
    aOut: 9,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 2,
    fl: 5,
    tfl: 8,
    built: 2017,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 228000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Sofia",
    nbhd: "Geo Milev",
    street: "ul. Kosta Lulchev",
    hn: "22",
    pc: "1111",
    lat: 42.6938,
    lng: 23.3612,
    area: 65,
    aLiv: 55,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 950,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Geo Milev",
    street: "ul. Kosta Lulchev",
    hn: "31",
    pc: "1111",
    lat: 42.6946,
    lng: 23.362,
    area: 158,
    aLiv: 132,
    aOut: 26,
    aLand: 360,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 345000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Geo Milev",
    street: "ul. Kosta Lulchev",
    hn: "40",
    pc: "1111",
    lat: 42.6954,
    lng: 23.3628,
    area: 275,
    aLiv: 235,
    aOut: 48,
    aLand: 750,
    aGar: 30,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2019,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 568000,
  },

  // ── Plovdiv · Hristo Smirnenski ──────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Hristo Smirnenski",
    street: "bul. Hristo Smirnenski",
    hn: "4",
    pc: "4006",
    lat: 42.1402,
    lng: 24.735,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 96000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Hristo Smirnenski",
    street: "bul. Hristo Smirnenski",
    hn: "12",
    pc: "4006",
    lat: 42.141,
    lng: 24.7358,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 112000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Hristo Smirnenski",
    street: "bul. Hristo Smirnenski",
    hn: "20",
    pc: "4006",
    lat: 42.1418,
    lng: 24.7366,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 1,
    tfl: 5,
    built: 2009,
    int: "UNFURNISHED",
    upk: "FAIR",
    heat: "BOILER",
    park: 0,
    price: 72000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Hristo Smirnenski",
    street: "bul. Hristo Smirnenski",
    hn: "29",
    pc: "4006",
    lat: 42.1426,
    lng: 24.7374,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 300,
    aGar: 16,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2008,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 218000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Hristo Smirnenski",
    street: "bul. Hristo Smirnenski",
    hn: "37",
    pc: "4006",
    lat: 42.1434,
    lng: 24.7382,
    area: 178,
    aLiv: 148,
    aOut: 28,
    aLand: 420,
    aGar: 20,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2012,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 272000,
  },

  // ── Plovdiv · Marasha ────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Marasha",
    street: "ul. Han Kubrat",
    hn: "5",
    pc: "4002",
    lat: 42.1558,
    lng: 24.755,
    area: 88,
    aLiv: 75,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 118000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Marasha",
    street: "ul. Han Kubrat",
    hn: "13",
    pc: "4002",
    lat: 42.1566,
    lng: 24.7558,
    area: 62,
    aLiv: 53,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 85000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Plovdiv",
    nbhd: "Marasha",
    street: "ul. Han Kubrat",
    hn: "21",
    pc: "4002",
    lat: 42.1574,
    lng: 24.7566,
    area: 75,
    aLiv: 64,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2014,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 600,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Marasha",
    street: "ul. Han Kubrat",
    hn: "30",
    pc: "4002",
    lat: 42.1582,
    lng: 24.7574,
    area: 162,
    aLiv: 136,
    aOut: 28,
    aLand: 380,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 245000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Marasha",
    street: "ul. Han Kubrat",
    hn: "39",
    pc: "4002",
    lat: 42.159,
    lng: 24.7582,
    area: 248,
    aLiv: 208,
    aOut: 44,
    aLand: 680,
    aGar: 28,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 368000,
  },

  // ── Varna · Center ───────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Center",
    street: "bul. Slivnitsa",
    hn: "3",
    pc: "9000",
    lat: 43.2096,
    lng: 27.9107,
    area: 105,
    aLiv: 90,
    aOut: 9,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 2,
    fl: 5,
    tfl: 7,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 198000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Center",
    street: "bul. Slivnitsa",
    hn: "11",
    pc: "9000",
    lat: 43.2104,
    lng: 27.9115,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 6,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 158000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Varna",
    nbhd: "Center",
    street: "bul. Slivnitsa",
    hn: "19",
    pc: "9000",
    lat: 43.2112,
    lng: 27.9123,
    area: 62,
    aLiv: 53,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2014,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 780,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Varna",
    nbhd: "Center",
    street: "ul. Knyaz Boris I",
    hn: "7",
    pc: "9000",
    lat: 43.212,
    lng: 27.9131,
    area: 165,
    aLiv: 138,
    aOut: 28,
    aLand: 380,
    aGar: 20,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 328000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Varna",
    nbhd: "Center",
    street: "ul. Knyaz Boris I",
    hn: "16",
    pc: "9000",
    lat: 43.2128,
    lng: 27.9139,
    area: 285,
    aLiv: 242,
    aOut: 52,
    aLand: 780,
    aGar: 32,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2019,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 545000,
  },

  // ── Varna · Chaika ───────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Chaika",
    street: "ul. Chaika",
    hn: "4",
    pc: "9023",
    lat: 43.238,
    lng: 27.875,
    area: 88,
    aLiv: 75,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2014,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 148000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Chaika",
    street: "ul. Chaika",
    hn: "12",
    pc: "9023",
    lat: 43.2388,
    lng: 27.8758,
    area: 62,
    aLiv: 53,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 112000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Varna",
    nbhd: "Chaika",
    street: "ul. Chaika",
    hn: "20",
    pc: "9023",
    lat: 43.2396,
    lng: 27.8766,
    area: 115,
    aLiv: 98,
    aOut: 10,
    aLand: null,
    aGar: null,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: 6,
    tfl: 9,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 1,
    price: 195000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Varna",
    nbhd: "Chaika",
    street: "ul. Chaika",
    hn: "29",
    pc: "9023",
    lat: 43.2404,
    lng: 27.8774,
    area: 178,
    aLiv: 150,
    aOut: 30,
    aLand: 420,
    aGar: 20,
    rooms: 5,
    bed: 4,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 2,
    price: 358000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Varna",
    nbhd: "Chaika",
    street: "ul. Chaika",
    hn: "38",
    pc: "9023",
    lat: 43.2412,
    lng: 27.8782,
    area: 268,
    aLiv: 228,
    aOut: 48,
    aLand: 760,
    aGar: 30,
    rooms: 6,
    bed: 5,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2020,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 498000,
  },

  // ── Burgas · Center ──────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Center",
    street: "bul. Aleko Bogoridi",
    hn: "5",
    pc: "8000",
    lat: 42.5048,
    lng: 27.4626,
    area: 92,
    aLiv: 79,
    aOut: 8,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 7,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "CENTRAL",
    park: 0,
    price: 145000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Center",
    street: "bul. Aleko Bogoridi",
    hn: "13",
    pc: "8000",
    lat: 42.5056,
    lng: 27.4634,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 118000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Burgas",
    nbhd: "Center",
    street: "bul. Aleko Bogoridi",
    hn: "21",
    pc: "8000",
    lat: 42.5064,
    lng: 27.4642,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 3,
    tfl: 8,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 620,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Center",
    street: "ul. Lermontov",
    hn: "6",
    pc: "8000",
    lat: 42.5072,
    lng: 27.465,
    area: 165,
    aLiv: 138,
    aOut: 28,
    aLand: 380,
    aGar: 20,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 272000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Center",
    street: "ul. Lermontov",
    hn: "15",
    pc: "8000",
    lat: 42.508,
    lng: 27.4658,
    area: 245,
    aLiv: 208,
    aOut: 44,
    aLand: 680,
    aGar: 28,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2018,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 415000,
  },

  // ── Burgas · Sarafovo ────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Sarafovo",
    street: "ul. Yanko Komitov",
    hn: "4",
    pc: "8014",
    lat: 42.537,
    lng: 27.518,
    area: 68,
    aLiv: 58,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 5,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 78000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Sarafovo",
    street: "ul. Yanko Komitov",
    hn: "12",
    pc: "8014",
    lat: 42.5378,
    lng: 27.5188,
    area: 148,
    aLiv: 122,
    aOut: 22,
    aLand: 320,
    aGar: 18,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2008,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 185000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Sarafovo",
    street: "ul. Yanko Komitov",
    hn: "21",
    pc: "8014",
    lat: 42.5386,
    lng: 27.5196,
    area: 248,
    aLiv: 210,
    aOut: 44,
    aLand: 650,
    aGar: 26,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2016,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 348000,
  },

  // ── Ruse · Zdravets ──────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Zdravets",
    street: "bul. Lipnik",
    hn: "5",
    pc: "7014",
    lat: 43.839,
    lng: 25.99,
    area: 78,
    aLiv: 66,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2009,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 72000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Zdravets",
    street: "bul. Lipnik",
    hn: "13",
    pc: "7014",
    lat: 43.8398,
    lng: 25.9908,
    area: 58,
    aLiv: 50,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2011,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 55000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Zdravets",
    street: "bul. Lipnik",
    hn: "22",
    pc: "7014",
    lat: 43.8406,
    lng: 25.9916,
    area: 145,
    aLiv: 120,
    aOut: 20,
    aLand: 290,
    aGar: 16,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2006,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 162000,
  },
  {
    sub: "villa",
    lt: "SELL",
    city: "Ruse",
    nbhd: "Zdravets",
    street: "bul. Lipnik",
    hn: "31",
    pc: "7014",
    lat: 43.8414,
    lng: 25.9924,
    area: 228,
    aLiv: 192,
    aOut: 38,
    aLand: 580,
    aGar: 26,
    rooms: 5,
    bed: 4,
    bath: 3,
    fl: null,
    tfl: 2,
    built: 2015,
    int: "FURNISHED",
    upk: "EXCELLENT",
    heat: "BOILER",
    park: 2,
    price: 285000,
  },

  // ── Stara Zagora ─────────────────────────────────────────────────────────────
  {
    sub: "apartment",
    lt: "SELL",
    city: "Stara Zagora",
    nbhd: "Center",
    street: "bul. Tsar Simeon Veliki",
    hn: "8",
    pc: "6000",
    lat: 42.424,
    lng: 25.6344,
    area: 88,
    aLiv: 75,
    aOut: 7,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 3,
    tfl: 7,
    built: 2013,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 88000,
  },
  {
    sub: "apartment",
    lt: "SELL",
    city: "Stara Zagora",
    nbhd: "Center",
    street: "bul. Tsar Simeon Veliki",
    hn: "16",
    pc: "6000",
    lat: 42.4248,
    lng: 25.6352,
    area: 62,
    aLiv: 53,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: 2,
    bed: 1,
    bath: 1,
    fl: 2,
    tfl: 6,
    built: 2010,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 68000,
  },
  {
    sub: "house",
    lt: "SELL",
    city: "Stara Zagora",
    nbhd: "Tri Chuchura",
    street: "ul. Ivan Vazov",
    hn: "4",
    pc: "6008",
    lat: 42.4156,
    lng: 25.622,
    area: 145,
    aLiv: 120,
    aOut: 20,
    aLand: 295,
    aGar: 16,
    rooms: 4,
    bed: 3,
    bath: 2,
    fl: null,
    tfl: 2,
    built: 2007,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "BOILER",
    park: 1,
    price: 172000,
  },
  {
    sub: "apartment",
    lt: "RENT",
    city: "Stara Zagora",
    nbhd: "Kazanski",
    street: "ul. Geo Milev",
    hn: "3",
    pc: "6010",
    lat: 42.4195,
    lng: 25.648,
    area: 72,
    aLiv: 62,
    aOut: 6,
    aLand: null,
    aGar: null,
    rooms: 3,
    bed: 2,
    bath: 1,
    fl: 4,
    tfl: 8,
    built: 2012,
    int: "FURNISHED",
    upk: "GOOD",
    heat: "CENTRAL",
    park: 0,
    price: 420,
  },
];

// ── Land plots & parking spaces ───────────────────────────────────────────────

const LAND_PARKING = [
  // 5 land plots — price = area × EUR/sqm; each gets 1 unique image from land pool
  {
    sub: "land",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Cherni Vrah",
    hn: "6",
    pc: "1407",
    lat: 42.68,
    lng: 23.32,
    area: 500,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 200000,
  },
  {
    sub: "land",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Kapana",
    street: "ul. Zlatarska",
    hn: "40",
    pc: "4000",
    lat: 42.151,
    lng: 24.751,
    area: 600,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 72000,
  },
  {
    sub: "land",
    lt: "SELL",
    city: "Varna",
    nbhd: "Sea Garden",
    street: "ul. Preslav",
    hn: "50",
    pc: "9000",
    lat: 43.2065,
    lng: 27.923,
    area: 800,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 160000,
  },
  {
    sub: "land",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Vitosha",
    street: "ul. Simeonsko shose",
    hn: "52",
    pc: "1700",
    lat: 42.6455,
    lng: 23.303,
    area: 350,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 175000,
  },
  {
    sub: "land",
    lt: "SELL",
    city: "Burgas",
    nbhd: "Lazur",
    street: "ul. Koprivshtitsa",
    hn: "35",
    pc: "8001",
    lat: 42.511,
    lng: 27.4795,
    area: 700,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 63000,
  },

  // 5 parking spaces — each gets 1 unique image from parking pool
  {
    sub: "parking",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Center",
    street: "bul. Vitosha",
    hn: "12",
    pc: "1000",
    lat: 42.698,
    lng: 23.322,
    area: 25,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 40000,
    covered: true,
    indoor: true,
  },
  {
    sub: "parking",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Lozenets",
    street: "ul. Krichim",
    hn: "8",
    pc: "1164",
    lat: 42.675,
    lng: 23.3245,
    area: 18,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 25000,
    covered: true,
    indoor: false,
  },
  {
    sub: "parking",
    lt: "SELL",
    city: "Varna",
    nbhd: "Sea Garden",
    street: "ul. Preslav",
    hn: "4",
    pc: "9000",
    lat: 43.2032,
    lng: 27.9195,
    area: 20,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 16000,
    covered: false,
    indoor: false,
  },
  {
    sub: "parking",
    lt: "SELL",
    city: "Plovdiv",
    nbhd: "Center",
    street: "ul. Hristo Botev",
    hn: "8",
    pc: "4000",
    lat: 43.1455,
    lng: 24.7505,
    area: 16,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 8000,
    covered: false,
    indoor: false,
  },
  {
    sub: "parking",
    lt: "SELL",
    city: "Sofia",
    nbhd: "Mladost",
    street: "bul. Aleksandar Malinov",
    hn: "16",
    pc: "1715",
    lat: 42.626,
    lng: 23.38,
    area: 22,
    aLiv: null,
    aOut: null,
    aLand: null,
    aGar: null,
    rooms: null,
    bed: null,
    bath: null,
    fl: null,
    tfl: null,
    built: null,
    int: null,
    upk: null,
    heat: null,
    park: null,
    price: 20000,
    covered: true,
    indoor: true,
  },
];

// ── Delete all data ───────────────────────────────────────────────────────────

async function deleteAllData() {
  console.log("Deleting all existing data...");
  await prisma.sentNotificationSavedSearch.deleteMany({});
  await prisma.recentlyViewedListing.deleteMany({});
  await prisma.savedListing.deleteMany({});
  await prisma.listingDescriptionKeyPoint.deleteMany({});
  await prisma.listingImage.deleteMany({});
  await prisma.listingPrice.updateMany({
    data: { updatedListingPriceId: null },
  });
  await prisma.listingPrice.deleteMany({});
  await prisma.address.deleteMany({});
  await prisma.invoice.deleteMany({});
  await prisma.subscription.deleteMany({});
  await prisma.listing.deleteMany({});
  await prisma.savedSearch.deleteMany({});
  await prisma.companyMembershipInvite.deleteMany({});
  await prisma.membership.deleteMany({});
  await prisma.applicationUser.deleteMany({});
  await prisma.company.deleteMany({});
  await prisma.subscriptionPlan.deleteMany({});
  console.log("All data deleted.");
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`Using ${SEED_IMAGE_SOURCE} seed images.`);
  await deleteAllData();

  // Create users
  const users = [];
  for (const u of USERS) {
    const slug = u.email.split("@")[0];
    const user = await prisma.applicationUser.create({
      data: {
        firebaseUID: `seed-${slug}`,
        email: u.email,
        displayName: u.displayName,
        providerId: "seed",
        phoneNumber: u.phone,
      },
    });
    users.push(user);
  }
  console.log(`Created ${users.length} users.`);

  // Create listings
  const now = Date.now();
  let idx = 0;

  for (const p of PROPS) {
    const user = users[idx % users.length];
    // Prime step (19) against 10-user cycle ensures each user's listings are
    // spread across all time windows, not clustered together.
    const daysAgo = 1 + ((idx * 19) % 135);
    const createdAt = new Date(now - daysAgo * MS_PER_DAY);
    const activeUntil = new Date(createdAt.getTime() + 8 * 30 * MS_PER_DAY);
    const latStr = (p.lat + (idx % 9) * 0.0004).toFixed(6);
    const lngStr = (p.lng + (idx % 9) * 0.0004).toFixed(6);
    const propType =
      p.sub === "land"
        ? "LAND"
        : p.sub === "parking"
          ? "PARKING"
          : p.sub === "apartment"
            ? "APARTMENT"
            : "HOUSE";

    await prisma.listing.create({
      data: {
        applicationUserId: user.id,
        listingType: p.lt,
        propertyType: propType,
        interiorType: p.int ?? null,
        upkeepType: p.upk ?? null,
        heatingType: p.heat ?? null,
        description: buildDescription(p),
        price: p.price,
        currency: "EUR",
        locality: p.city,
        areaTotal: p.area ?? null,
        areaLiving: p.aLiv ?? null,
        areaLand: p.aLand ?? null,
        areaOutside: p.aOut ?? null,
        areaGarage: p.aGar ?? null,
        streetName: p.street,
        houseNumber: p.hn,
        postalCode: p.pc,
        latitude: latStr,
        longitude: lngStr,
        rooms: p.rooms ?? null,
        bedrooms: p.bed ?? null,
        bathrooms: p.bath ?? null,
        parking: p.park > 0 ? p.park : null,
        constructedYear: p.built
          ? new Date(`${p.built}-06-01T00:00:00.000Z`)
          : null,
        floorNumber: p.fl ?? null,
        numberOfFloorsProperty: p.sub !== "apartment" ? (p.tfl ?? null) : null,
        numberOfFloorsCommon: p.tfl ?? null,
        active: true,
        activeUntil,
        createdAt,
        Address: {
          create: [
            {
              streetNumber: p.hn,
              route: p.street,
              administrativeAreaLevelOne: "Bulgaria",
              locality: p.city,
              postalCode: p.pc,
              neighborhood: p.nbhd,
              latitude: latStr,
              longitude: lngStr,
              showExactLocation: true,
            },
          ],
        },
        ListingImage: {
          create: buildImages(p.sub, idx, !!p.aOut),
        },
        ListingPrice: {
          create: buildPriceHistory(p.price, idx, createdAt),
        },
        listingDescriptionKeyPoints: {
          create: buildKeyPoints(p).map(([title, description]) => ({
            title,
            description,
          })),
        },
      },
    });

    idx++;
  }

  // Land and parking
  for (const p of LAND_PARKING) {
    const user = users[idx % users.length];
    const daysAgo = 1 + ((idx * 19) % 135);
    const createdAt = new Date(now - daysAgo * MS_PER_DAY);
    const activeUntil = new Date(createdAt.getTime() + 8 * 30 * MS_PER_DAY);
    const latStr = (p.lat + (idx % 9) * 0.0004).toFixed(6);
    const lngStr = (p.lng + (idx % 9) * 0.0004).toFixed(6);
    const propType = p.sub === "land" ? "LAND" : "PARKING";

    await prisma.listing.create({
      data: {
        applicationUserId: user.id,
        listingType: p.lt,
        propertyType: propType,
        interiorType: null,
        upkeepType: null,
        heatingType: null,
        description: buildDescription(p),
        price: p.price,
        currency: "EUR",
        locality: p.city,
        areaTotal: p.area ?? null,
        areaLiving: null,
        areaLand: null,
        areaOutside: null,
        areaGarage: null,
        streetName: p.street,
        houseNumber: p.hn,
        postalCode: p.pc,
        latitude: latStr,
        longitude: lngStr,
        rooms: null,
        bedrooms: null,
        bathrooms: null,
        parking: null,
        constructedYear: null,
        floorNumber: null,
        numberOfFloorsProperty: null,
        numberOfFloorsCommon: null,
        active: true,
        activeUntil,
        createdAt,
        Address: {
          create: [
            {
              streetNumber: p.hn,
              route: p.street,
              administrativeAreaLevelOne: "Bulgaria",
              locality: p.city,
              postalCode: p.pc,
              neighborhood: p.nbhd,
              latitude: latStr,
              longitude: lngStr,
              showExactLocation: true,
            },
          ],
        },
        ListingImage: {
          create: buildImages(p.sub, idx, false),
        },
        ListingPrice: {
          create: buildPriceHistory(p.price, idx, createdAt),
        },
        listingDescriptionKeyPoints: {
          create: buildKeyPoints(p).map(([title, description]) => ({
            title,
            description,
          })),
        },
      },
    });

    idx++;
  }

  // Summary
  const allProps = [...PROPS, ...LAND_PARKING];
  const apts = allProps.filter((p) => p.sub === "apartment").length;
  const houses = allProps.filter((p) => p.sub === "house").length;
  const villas = allProps.filter((p) => p.sub === "villa").length;
  const lands = allProps.filter((p) => p.sub === "land").length;
  const parkings = allProps.filter((p) => p.sub === "parking").length;
  const sells = allProps.filter((p) => p.lt === "SELL").length;
  const rents = allProps.filter((p) => p.lt === "RENT").length;

  console.log(`\nCreated ${idx} listings:`);
  console.log(
    `  ${apts} apartments, ${houses} houses, ${villas} villas, ${lands} land plots, ${parkings} parking spaces`,
  );
  console.log(`  ${sells} for sale, ${rents} for rent`);
  console.log(`  Across ${users.length} users`);

  const cities = [...new Set(allProps.map((p) => p.city))];
  for (const city of cities) {
    const count = allProps.filter((p) => p.city === city).length;
    console.log(`  ${city}: ${count}`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
